# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Every Vagrant virtual environment requires a box to build off of.
    config.vm.box = "ubuntu/trusty64"
    config.vm.provision :shell, path: "bootstrap.sh"

    # Name the virtual machine
    config.vm.provider "virtualbox" do |v|
      v.name = "docker-test-machine"
    end

    # Sets the machine hostname
    config.vm.hostname = "dockertest.machine"

    # Create a public network, which generally matched to bridged network.
    # Bridged networks make the machine appear as another physical device on
    # your network.
    config.vm.network "private_network", ip: "192.168.100.10"
end
